<a href="https://colab.research.google.com/github/Nikesh5005/ML_PROJ/blob/main/Dynamic__Pricing_Engine_Retail.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
df = pd.read_csv("/content/drive/MyDrive/retail_store_inventory.csv")
df

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73095,2024-01-01,S005,P0016,Furniture,East,96,8,127,18.46,73.73,20,Snowy,0,72.45,Winter
73096,2024-01-01,S005,P0017,Toys,North,313,51,101,48.43,82.57,10,Cloudy,0,83.78,Autumn
73097,2024-01-01,S005,P0018,Clothing,West,278,36,151,39.65,11.11,10,Rainy,0,10.91,Winter
73098,2024-01-01,S005,P0019,Toys,East,374,264,21,270.52,53.14,20,Rainy,0,55.80,Spring
73099,2024-01-01,S005,P0020,Groceries,East,117,6,165,2.33,78.39,20,Rainy,1,79.52,Spring

In [11]:
df=df.drop(labels=['Store ID','Product ID','Demand Forecast'],axis=1)

In [13]:
df

,Date,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
0,2022-01-01,Groceries,North,231,127,55,33.50,20,Rainy,0,29.69,Autumn
1,2022-01-01,Toys,South,204,150,66,63.01,20,Sunny,0,66.16,Autumn
2,2022-01-01,Toys,West,102,65,51,27.99,10,Sunny,1,31.32,Summer
3,2022-01-01,Toys,North,469,61,164,32.72,10,Cloudy,1,34.74,Autumn
4,2022-01-01,Electronics,East,166,14,135,73.64,0,Sunny,0,68.95,Summer
...,...,...,...,...,...,...,...,...,...,...,...,...
73095,2024-01-01,Furniture,East,96,8,127,73.73,20,Snowy,0,72.45,Winter
73096,2024-01-01,Toys,North,313,51,101,82.57,10,Cloudy,0,83.78,Autumn
73097,2024-01-01,Clothing,West,278,36,151,11.11,10,Rainy,0,10.91,Winter
73098,2024-01-01,Toys,East,374,264,21,53.14,20,Rainy,0,55.80,Spring
73099,2024-01-01,Groceries,East,117,6,165,78.39,20,Rainy,1,79.52,Spring

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73100 entries, 0 to 73099
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                73100 non-null  object
 1   Category            73100 non-null  object
 2   Region              73100 non-null  object
 3   Inventory Level     73100 non-null  int64
 4   Units Sold          73100 non-null  int64
 5   Units Ordered       73100 non-null  int64
 6   Price               73100 non-null  float64
 7   Discount            73100 non-null  int64
 8   Weather Condition   73100 non-null  object
 9   Holiday/Promotion   73100 non-null  int64
 10  Competitor Pricing  73100 non-null  float64
 11  Seasonality         73100 non-null  object
dtypes: float64(2), int64(5), object(5)
memory usage: 6.7+ MB

In [16]:
df['Date']=pd.to_datetime(df['Date'])

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73100 entries, 0 to 73099
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                73100 non-null  datetime64[ns]
 1   Category            73100 non-null  object
 2   Region              73100 non-null  object
 3   Inventory Level     73100 non-null  int64
 4   Units Sold          73100 non-null  int64
 5   Units Ordered       73100 non-null  int64
 6   Price               73100 non-null  float64
 7   Discount            73100 non-null  int64
 8   Weather Condition   73100 non-null  object
 9   Holiday/Promotion   73100 non-null  int64
 10  Competitor Pricing  73100 non-null  float64
 11  Seasonality         73100 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(5), object(4)
memory usage: 6.7+ MB